import '../models/models.dart';

// Mock data generator
class MockDataService {
  static List<Player> generateMockPlayers() {
    final basePlayers = [
      // STRIKERS/CENTROAVANTES
      Player(
        id: 'player_1',
        name: 'Marcus Silva',
        nickname: 'Marcão',
        birthYear: 1998,
        age: 26,
        nationality: 'Brasil',
        city: 'São Paulo',
        languages: 'Português, Inglês',
        club: 'Flamengo',
        league: 'Série A',
        country: 'Brasil',
        contractStatus: ContractStatus.long,
        agent: 'Jorge Mendes',
        status: PlayerStatus.professional,
        positions: [PlayerPosition.st, PlayerPosition.ss],
        primaryPosition: PlayerPosition.st,
        height: 185,
        weight: 82,
        bodyType: BodyType.athletic,
        preferredFoot: Foot.right,
        isVerified: true,
        paceAcceleration: 88,
        topSpeed: 92,
        stamina: 85,
        strength: 84,
        agility: 86,
        balance: 82,
        jump: 89,
        passingShort: 76,
        passingLong: 72,
        progressivePass: 74,
        firstTouch: 84,
        ballControl: 86,
        dribbling: 88,
        crossing: 70,
        finishing: 92,
        shotPower: 90,
        heading: 88,
        tackling: 42,
        interception: 38,
        positioning: 89,
        aerialDuels: 87,
        groundDuels: 79,
        weakFootQuality: 74,
        buildUp: 65,
        pressResistance: 78,
        decisionMaking: 85,
        scanning: 80,
        offBallMovement: 90,
        defensiveLine: 35,
        pressing: 72,
        recoveryRuns: 68,
        composure: 86,
        aggression: 78,
        leadership: 82,
        teamwork: 84,
        resilience: 85,
        coachability: 88,
        professionalism: 89,
        gameIQ: 87,
        riskTaking: 76,
        discipline: 84,
        styleTags: [
          'Finalizador',
          'Atacante móvel',
          'Forte no 1v1',
          'Chega na área',
        ],
        roles: ['Finalizador', 'Atacante de área'],
        strengths: [
          'Finalização precisa',
          'Movimentação fora de bola excelente',
          'Aceleração rápida',
          'Inteligência tática',
          'Força física',
        ],
        weaknesses: [
          'Defesa fraca',
          'Cruzamento impreciso',
          'Paciência reduzida',
        ],
        bestSystems: ['4-3-3', '4-2-3-1', '3-5-2'],
        bestBlock: TacticalBlock.high,
        description:
            'Atacante completo com excelente finalização e movimentação. Forte em espaços abertos e duelos aéreos. Polivalente na área.',
        estimatedValueMin: 25000000,
        estimatedValueMax: 35000000,
        salaryMin: 200000,
        salaryMax: 280000,
        potential: Potential.high,
        transferRisk: TransferRisk.low,
        isReadyToLevelUp: true,
        injuryHistory: [],
        injuryRisk: InjuryRisk.low,
        photoUrl: 'https://via.placeholder.com/200/FF6B6B/FFFFFF?text=M.Silva',
        highlightVideos: ['video1', 'video2', 'video3'],
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now(),
        followers: 15000,
        savedByUsers: [],
      ),
      // DEFENDERS
      Player(
        id: 'player_2',
        name: 'Pedro Rocha',
        nickname: 'Rock',
        birthYear: 1996,
        age: 28,
        nationality: 'Portugal',
        city: 'Lisboa',
        languages: 'Português, Inglês, Espanhol',
        club: 'Benfica',
        league: 'Primeira Liga',
        country: 'Portugal',
        contractStatus: ContractStatus.long,
        agent: 'Gestifute',
        status: PlayerStatus.professional,
        positions: [PlayerPosition.cb, PlayerPosition.rcb],
        primaryPosition: PlayerPosition.cb,
        height: 189,
        weight: 88,
        bodyType: BodyType.muscular,
        preferredFoot: Foot.right,
        isVerified: true,
        paceAcceleration: 78,
        topSpeed: 80,
        stamina: 88,
        strength: 92,
        agility: 74,
        balance: 86,
        jump: 92,
        passingShort: 84,
        passingLong: 78,
        progressivePass: 80,
        firstTouch: 82,
        ballControl: 80,
        dribbling: 72,
        crossing: 58,
        finishing: 38,
        shotPower: 82,
        heading: 94,
        tackling: 92,
        interception: 88,
        positioning: 91,
        aerialDuels: 95,
        groundDuels: 90,
        weakFootQuality: 68,
        buildUp: 85,
        pressResistance: 88,
        decisionMaking: 86,
        scanning: 87,
        offBallMovement: 72,
        defensiveLine: 88,
        pressing: 78,
        recoveryRuns: 82,
        composure: 89,
        aggression: 80,
        leadership: 88,
        teamwork: 86,
        resilience: 90,
        coachability: 85,
        professionalism: 88,
        gameIQ: 87,
        riskTaking: 62,
        discipline: 89,
        styleTags: [
          'Construtor',
          'Marcador',
          'Forte no 1v1',
          'Bom em bolas longas',
        ],
        roles: ['Zagueiro construtor', 'Líder defensivo'],
        strengths: [
          'Antecipação excepcional',
          'Força aérea dominante',
          'Construção de jogo',
          'Liderança em campo',
          'Consistência',
        ],
        weaknesses: ['Velocidade limitada', 'Agilidade reduzida'],
        bestSystems: ['4-3-3', '4-4-2', '3-5-2'],
        bestBlock: TacticalBlock.high,
        description:
            'Zagueiro experiente e líder. Excelente em defesa aérea e construção. Pilha defensiva confiável.',
        estimatedValueMin: 18000000,
        estimatedValueMax: 26000000,
        salaryMin: 150000,
        salaryMax: 200000,
        potential: Potential.medium,
        transferRisk: TransferRisk.low,
        isReadyToLevelUp: false,
        injuryHistory: [
          InjuryHistory(
            year: 2022,
            type: 'Lesão muscular',
            monthsOut: 2,
            recurrenceRisk: InjuryRisk.low,
          ),
        ],
        injuryRisk: InjuryRisk.low,
        photoUrl: 'https://via.placeholder.com/200/4ECDC4/FFFFFF?text=P.Rocha',
        highlightVideos: ['video1', 'video2'],
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now(),
        followers: 12000,
        savedByUsers: [],
      ),
      // MIDFIELDERS
      Player(
        id: 'player_3',
        name: 'João Costa',
        nickname: null,
        birthYear: 1999,
        age: 25,
        nationality: 'Brasil',
        city: 'Rio de Janeiro',
        languages: 'Português, Inglês',
        club: 'Vasco da Gama',
        league: 'Série A',
        country: 'Brasil',
        contractStatus: ContractStatus.medium,
        agent: null,
        status: PlayerStatus.professional,
        positions: [PlayerPosition.cm, PlayerPosition.dm],
        primaryPosition: PlayerPosition.cm,
        height: 178,
        weight: 72,
        bodyType: BodyType.athletic,
        preferredFoot: Foot.left,
        isVerified: false,
        paceAcceleration: 82,
        topSpeed: 84,
        stamina: 92,
        strength: 78,
        agility: 85,
        balance: 84,
        jump: 76,
        passingShort: 90,
        passingLong: 88,
        progressivePass: 87,
        firstTouch: 88,
        ballControl: 89,
        dribbling: 84,
        crossing: 82,
        finishing: 68,
        shotPower: 76,
        heading: 72,
        tackling: 80,
        interception: 82,
        positioning: 84,
        aerialDuels: 74,
        groundDuels: 82,
        weakFootQuality: 78,
        buildUp: 90,
        pressResistance: 85,
        decisionMaking: 88,
        scanning: 89,
        offBallMovement: 86,
        defensiveLine: 76,
        pressing: 84,
        recoveryRuns: 86,
        composure: 87,
        aggression: 76,
        leadership: 82,
        teamwork: 90,
        resilience: 84,
        coachability: 88,
        professionalism: 86,
        gameIQ: 89,
        riskTaking: 74,
        discipline: 85,
        styleTags: ['Construtor', 'Vertical', 'Criativo', 'Chega na área'],
        roles: ['Meia organizador', 'Lateral avançado'],
        strengths: [
          'Passa progressivas precisa',
          'Leitura de jogo',
          'Recuperação de bola',
          'Criatividade',
          'Trabalho em equipe',
        ],
        weaknesses: ['Finalização imprecisa', 'Aéreo fraco', 'Força limitada'],
        bestSystems: ['4-3-3', '4-2-3-1', '3-4-3'],
        bestBlock: TacticalBlock.medium,
        description:
            'Meia versátil com ótima visão de jogo. Especialista em passes progressivos e recuperação.',
        estimatedValueMin: 12000000,
        estimatedValueMax: 18000000,
        salaryMin: 100000,
        salaryMax: 140000,
        potential: Potential.high,
        transferRisk: TransferRisk.medium,
        isReadyToLevelUp: true,
        injuryHistory: [],
        injuryRisk: InjuryRisk.low,
        photoUrl: 'https://via.placeholder.com/200/95E1D3/FFFFFF?text=J.Costa',
        highlightVideos: ['video1', 'video2', 'video3', 'video4'],
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now(),
        followers: 18000,
        savedByUsers: [],
      ),
      // WINGERS
      Player(
        id: 'player_4',
        name: 'Felipe Santos',
        nickname: 'Formiga',
        birthYear: 2001,
        age: 23,
        nationality: 'Brasil',
        city: 'Fortaleza',
        languages: 'Português',
        club: 'Cebolinha FC',
        league: 'Série A',
        country: 'Brasil',
        contractStatus: ContractStatus.short,
        agent: null,
        status: PlayerStatus.base,
        positions: [PlayerPosition.rw, PlayerPosition.am],
        primaryPosition: PlayerPosition.rw,
        height: 172,
        weight: 68,
        bodyType: BodyType.lean,
        preferredFoot: Foot.right,
        isVerified: false,
        paceAcceleration: 92,
        topSpeed: 95,
        stamina: 88,
        strength: 70,
        agility: 90,
        balance: 88,
        jump: 78,
        passingShort: 78,
        passingLong: 72,
        progressivePass: 76,
        firstTouch: 86,
        ballControl: 90,
        dribbling: 94,
        crossing: 84,
        finishing: 82,
        shotPower: 80,
        heading: 66,
        tackling: 54,
        interception: 52,
        positioning: 82,
        aerialDuels: 68,
        groundDuels: 72,
        weakFootQuality: 64,
        buildUp: 68,
        pressResistance: 76,
        decisionMaking: 78,
        scanning: 76,
        offBallMovement: 86,
        defensiveLine: 42,
        pressing: 74,
        recoveryRuns: 64,
        composure: 80,
        aggression: 72,
        leadership: 74,
        teamwork: 80,
        resilience: 82,
        coachability: 86,
        professionalism: 80,
        gameIQ: 80,
        riskTaking: 84,
        discipline: 76,
        styleTags: ['Criativo', 'Forte no 1v1', 'Agilidade', 'Dribble'],
        roles: ['Ponta criativa', 'Segundo atacante'],
        strengths: [
          'Dribble excepcional',
          'Velocidade explosiva',
          'Cruzamento preciso',
          'Finalização',
          'Criatividade no 1v1',
        ],
        weaknesses: [
          'Defesa fraca',
          'Inconsistência',
          'Força limitada',
          'Tomadas de decisão questionáveis',
        ],
        bestSystems: ['4-3-3', '3-5-2'],
        bestBlock: TacticalBlock.high,
        description:
            'Jovem ponta com habilidade técnica excepcional. Precisa amadurecer defensivamente. Grande potencial em sistemas ofensivos.',
        estimatedValueMin: 8000000,
        estimatedValueMax: 14000000,
        salaryMin: 80000,
        salaryMax: 120000,
        potential: Potential.high,
        transferRisk: TransferRisk.high,
        isReadyToLevelUp: true,
        injuryHistory: [
          InjuryHistory(
            year: 2023,
            type: 'Distensão muscular',
            monthsOut: 1,
            recurrenceRisk: InjuryRisk.high,
          ),
        ],
        injuryRisk: InjuryRisk.medium,
        photoUrl: 'https://via.placeholder.com/200/F38181/FFFFFF?text=F.Santos',
        highlightVideos: ['video1', 'video2', 'video3', 'video4', 'video5'],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now(),
        followers: 22000,
        savedByUsers: [],
      ),
      // GOALKEEPERS
      Player(
        id: 'player_5',
        name: 'Rafael Borges',
        nickname: null,
        birthYear: 1994,
        age: 30,
        nationality: 'Brasil',
        city: 'São Paulo',
        languages: 'Português, Inglês',
        club: 'Palmeiras',
        league: 'Série A',
        country: 'Brasil',
        contractStatus: ContractStatus.long,
        agent: 'Jorge Mendes',
        status: PlayerStatus.professional,
        positions: [PlayerPosition.gk],
        primaryPosition: PlayerPosition.gk,
        height: 188,
        weight: 84,
        bodyType: BodyType.athletic,
        preferredFoot: Foot.right,
        isVerified: true,
        paceAcceleration: 72,
        topSpeed: 74,
        stamina: 86,
        strength: 82,
        agility: 80,
        balance: 84,
        jump: 88,
        passingShort: 76,
        passingLong: 70,
        progressivePass: 68,
        firstTouch: 78,
        ballControl: 72,
        dribbling: 60,
        crossing: 0,
        finishing: 0,
        shotPower: 0,
        heading: 0,
        tackling: 0,
        interception: 0,
        positioning: 90,
        aerialDuels: 91,
        groundDuels: 78,
        weakFootQuality: 62,
        buildUp: 78,
        pressResistance: 82,
        decisionMaking: 86,
        scanning: 88,
        offBallMovement: 0,
        defensiveLine: 0,
        pressing: 0,
        recoveryRuns: 0,
        composure: 90,
        aggression: 68,
        leadership: 86,
        teamwork: 84,
        resilience: 88,
        coachability: 86,
        professionalism: 90,
        gameIQ: 88,
        riskTaking: 64,
        discipline: 90,
        styleTags: ['Conservador', 'Distribuidor', 'Aéreo'],
        roles: ['Goleiro distribuidor', 'Goleiro tradicional'],
        strengths: [
          'Distribuição de bola',
          'Segurança sob pressão',
          'Comando de área',
          'Reflexos rápidos',
          'Liderança',
        ],
        weaknesses: ['Sai do gol com frequência', 'Pés frágeis ocasionalmente'],
        bestSystems: ['4-3-3', '4-2-3-1', 'Qualquer sistema'],
        bestBlock: TacticalBlock.high,
        description:
            'Goleiro experiente com distribuição fluida e segurança acima da média. Líder na zaga.',
        estimatedValueMin: 6000000,
        estimatedValueMax: 10000000,
        salaryMin: 120000,
        salaryMax: 160000,
        potential: Potential.low,
        transferRisk: TransferRisk.low,
        isReadyToLevelUp: false,
        injuryHistory: [],
        injuryRisk: InjuryRisk.low,
        photoUrl: 'https://via.placeholder.com/200/AA96DA/FFFFFF?text=R.Borges',
        highlightVideos: ['video1', 'video2'],
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now(),
        followers: 8000,
        savedByUsers: [],
      ),
      // FULLBACKS
      Player(
        id: 'player_6',
        name: 'Lucas Ferreira',
        nickname: 'Lucão',
        birthYear: 2000,
        age: 24,
        nationality: 'Brasil',
        city: 'Belo Horizonte',
        languages: 'Português',
        club: 'Atlético Mineiro',
        league: 'Série A',
        country: 'Brasil',
        contractStatus: ContractStatus.medium,
        agent: null,
        status: PlayerStatus.professional,
        positions: [PlayerPosition.lb, PlayerPosition.lwb],
        primaryPosition: PlayerPosition.lb,
        height: 180,
        weight: 74,
        bodyType: BodyType.athletic,
        preferredFoot: Foot.left,
        isVerified: false,
        paceAcceleration: 88,
        topSpeed: 90,
        stamina: 90,
        strength: 80,
        agility: 86,
        balance: 84,
        jump: 80,
        passingShort: 82,
        passingLong: 78,
        progressivePass: 80,
        firstTouch: 84,
        ballControl: 84,
        dribbling: 86,
        crossing: 88,
        finishing: 62,
        shotPower: 76,
        heading: 78,
        tackling: 86,
        interception: 84,
        positioning: 86,
        aerialDuels: 82,
        groundDuels: 86,
        weakFootQuality: 72,
        buildUp: 80,
        pressResistance: 82,
        decisionMaking: 82,
        scanning: 80,
        offBallMovement: 84,
        defensiveLine: 82,
        pressing: 84,
        recoveryRuns: 88,
        composure: 84,
        aggression: 78,
        leadership: 80,
        teamwork: 86,
        resilience: 84,
        coachability: 86,
        professionalism: 84,
        gameIQ: 82,
        riskTaking: 76,
        discipline: 82,
        styleTags: ['Ala ofensivo', 'Construtor', 'Vertical', 'Equilibrado'],
        roles: ['Lateral avançado', 'Ala defensivo'],
        strengths: [
          'Cruzamento preciso',
          'Ataque em profundidade',
          'Resistência',
          'Um contra um',
          'Ritmo de jogo',
        ],
        weaknesses: ['Concentração ocasional', 'Força aérea média'],
        bestSystems: ['4-3-3', '4-2-3-1', '3-5-2'],
        bestBlock: TacticalBlock.high,
        description:
            'Lateral versátil com bom ataque e defesa sólida. Crescimento consistente.',
        estimatedValueMin: 14000000,
        estimatedValueMax: 20000000,
        salaryMin: 110000,
        salaryMax: 150000,
        potential: Potential.high,
        transferRisk: TransferRisk.medium,
        isReadyToLevelUp: true,
        injuryHistory: [],
        injuryRisk: InjuryRisk.low,
        photoUrl:
            'https://via.placeholder.com/200/FCBAD3/FFFFFF?text=L.Ferreira',
        highlightVideos: ['video1', 'video2', 'video3'],
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
        updatedAt: DateTime.now(),
        followers: 16000,
        savedByUsers: [],
      ),
      // DEFENSIVE MIDFIELDER
      Player(
        id: 'player_7',
        name: 'André Silva',
        nickname: 'Aндрé',
        birthYear: 1997,
        age: 27,
        nationality: 'Portugal',
        city: 'Porto',
        languages: 'Português, Inglês, Francês',
        club: 'FC Porto',
        league: 'Primeira Liga',
        country: 'Portugal',
        contractStatus: ContractStatus.long,
        agent: 'Mendes Sports Management',
        status: PlayerStatus.professional,
        positions: [PlayerPosition.dm, PlayerPosition.cm],
        primaryPosition: PlayerPosition.dm,
        height: 182,
        weight: 80,
        bodyType: BodyType.athletic,
        preferredFoot: Foot.right,
        isVerified: true,
        paceAcceleration: 82,
        topSpeed: 84,
        stamina: 92,
        strength: 88,
        agility: 80,
        balance: 82,
        jump: 82,
        passingShort: 88,
        passingLong: 84,
        progressivePass: 86,
        firstTouch: 86,
        ballControl: 86,
        dribbling: 78,
        crossing: 76,
        finishing: 58,
        shotPower: 80,
        heading: 84,
        tackling: 92,
        interception: 90,
        positioning: 91,
        aerialDuels: 86,
        groundDuels: 90,
        weakFootQuality: 76,
        buildUp: 88,
        pressResistance: 90,
        decisionMaking: 89,
        scanning: 88,
        offBallMovement: 80,
        defensiveLine: 88,
        pressing: 90,
        recoveryRuns: 92,
        composure: 88,
        aggression: 82,
        leadership: 86,
        teamwork: 90,
        resilience: 88,
        coachability: 86,
        professionalism: 90,
        gameIQ: 89,
        riskTaking: 68,
        discipline: 90,
        styleTags: ['Marcador', 'Construtor', 'Agressivo', 'Equilibrado'],
        roles: ['Meia-volante', 'Protetor de defesa'],
        strengths: [
          'Interceptações precisas',
          'Cobertura defensiva',
          'Resistência física',
          'Passes verticais',
          'Liderança defensiva',
        ],
        weaknesses: ['Finalização limitada', 'Cruzamentos imprecisos'],
        bestSystems: ['4-3-3', '4-2-3-1', '4-4-2'],
        bestBlock: TacticalBlock.medium,
        description:
            'Volante polivalente e confiável. Excelente na proteção defensiva e distribuição.',
        estimatedValueMin: 20000000,
        estimatedValueMax: 28000000,
        salaryMin: 160000,
        salaryMax: 220000,
        potential: Potential.medium,
        transferRisk: TransferRisk.low,
        isReadyToLevelUp: false,
        injuryHistory: [
          InjuryHistory(
            year: 2021,
            type: 'Lesão no joelho',
            monthsOut: 3,
            recurrenceRisk: InjuryRisk.low,
          ),
        ],
        injuryRisk: InjuryRisk.low,
        photoUrl: 'https://via.placeholder.com/200/FFFCC7/FFFFFF?text=A.Silva',
        highlightVideos: ['video1', 'video2', 'video3'],
        createdAt: DateTime.now().subtract(const Duration(days: 50)),
        updatedAt: DateTime.now(),
        followers: 14000,
        savedByUsers: [],
      ),
      // ATTACKING MIDFIELDER
      Player(
        id: 'player_8',
        name: 'Neymar Jr',
        nickname: 'Ney',
        birthYear: 1992,
        age: 32,
        nationality: 'Brasil',
        city: 'Praia Grande',
        languages: 'Português, Inglês, Francês, Espanhol',
        club: 'Al-Hilal',
        league: 'Saudi Pro League',
        country: 'Arábia Saudita',
        contractStatus: ContractStatus.long,
        agent: 'Pai',
        status: PlayerStatus.professional,
        positions: [PlayerPosition.lw, PlayerPosition.am, PlayerPosition.ss],
        primaryPosition: PlayerPosition.am,
        height: 175,
        weight: 68,
        bodyType: BodyType.lean,
        preferredFoot: Foot.left,
        isVerified: true,
        paceAcceleration: 86,
        topSpeed: 88,
        stamina: 82,
        strength: 76,
        agility: 92,
        balance: 90,
        jump: 82,
        passingShort: 88,
        passingLong: 86,
        progressivePass: 89,
        firstTouch: 92,
        ballControl: 95,
        dribbling: 96,
        crossing: 88,
        finishing: 86,
        shotPower: 86,
        heading: 72,
        tackling: 48,
        interception: 46,
        positioning: 88,
        aerialDuels: 70,
        groundDuels: 76,
        weakFootQuality: 86,
        buildUp: 86,
        pressResistance: 88,
        decisionMaking: 88,
        scanning: 90,
        offBallMovement: 92,
        defensiveLine: 38,
        pressing: 72,
        recoveryRuns: 66,
        composure: 88,
        aggression: 74,
        leadership: 84,
        teamwork: 82,
        resilience: 86,
        coachability: 80,
        professionalism: 82,
        gameIQ: 90,
        riskTaking: 88,
        discipline: 76,
        styleTags: ['Criativo', 'Forte no 1v1', 'Vertical', 'Polivalente'],
        roles: ['Extremo criativo', 'Meia organizador'],
        strengths: [
          'Dribble de elite',
          'Visão de jogo excepcional',
          'Versatilidade tática',
          'Chute de fora',
          'Movimentação inteligente',
        ],
        weaknesses: [
          'Defesa praticamente nula',
          'Disciplina questionável',
          'Lesões recorrentes',
        ],
        bestSystems: ['4-3-3', '3-5-2', '4-2-3-1'],
        bestBlock: TacticalBlock.high,
        description:
            'Estrela global com criatividade e dribble únicos. Exigente de sistemas ofensivos. Experiência internacional comprovada.',
        estimatedValueMin: 15000000,
        estimatedValueMax: 25000000,
        salaryMin: 300000,
        salaryMax: 450000,
        potential: Potential.medium,
        transferRisk: TransferRisk.high,
        isReadyToLevelUp: false,
        injuryHistory: [
          InjuryHistory(
            year: 2022,
            type: 'Lesão no tornozelo',
            monthsOut: 4,
            recurrenceRisk: InjuryRisk.high,
          ),
          InjuryHistory(
            year: 2023,
            type: 'Lesão muscular',
            monthsOut: 3,
            recurrenceRisk: InjuryRisk.high,
          ),
        ],
        injuryRisk: InjuryRisk.high,
        photoUrl: 'https://via.placeholder.com/200/FFB84D/FFFFFF?text=Neymar',
        highlightVideos: [
          'video1',
          'video2',
          'video3',
          'video4',
          'video5',
          'video6',
        ],
        createdAt: DateTime.now().subtract(const Duration(days: 80)),
        updatedAt: DateTime.now(),
        followers: 500000,
        savedByUsers: [],
      ),
    ];

    final extraPlayers = <Player>[];
    final positions = PlayerPosition.values;
    final clubs = [
      'Corinthians',
      'Palmeiras',
      'Santos',
      'Grêmio',
      'Internacional',
      'Bahia',
      'Athletico',
      'Fortaleza',
      'Sporting',
      'Porto',
      'Braga',
      'Ajax',
      'PSV',
      'Rennes',
      'Sevilla',
    ];
    final leagues = [
      'Série A',
      'Série B',
      'Primeira Liga',
      'Eredivisie',
      'La Liga',
      'Ligue 1',
    ];
    final countries = [
      'Brasil',
      'Portugal',
      'Argentina',
      'Colômbia',
      'Uruguai',
      'Espanha',
      'França',
    ];

    int rating(int base, int i) => 45 + ((base + i * 7) % 55);

    for (int i = basePlayers.length + 1; i <= 60; i++) {
      final position = positions[(i - 1) % positions.length];
      final secondary = positions[i % positions.length];
      final club = clubs[(i - 1) % clubs.length];
      final league = leagues[(i - 1) % leagues.length];
      final country = countries[(i - 1) % countries.length];
      final age = 17 + (i % 15);
      final birthYear = DateTime.now().year - age;
      final createdBy = i % 3 == 0 ? 'user_${(i % 30) + 1}' : null;

      extraPlayers.add(
        Player(
          id: 'player_$i',
          name: 'Jogador $i',
          nickname: 'Craque $i',
          birthYear: birthYear,
          age: age,
          nationality: country,
          city: 'Cidade $i',
          languages: 'Português',
          club: club,
          league: league,
          country: country,
          contractStatus:
              ContractStatus.values[i % ContractStatus.values.length],
          agent: 'Agente $i',
          status: PlayerStatus.values[i % PlayerStatus.values.length],
          positions: [position, secondary],
          primaryPosition: position,
          height: 170 + (i % 20),
          weight: 65 + (i % 20),
          bodyType: BodyType.values[i % BodyType.values.length],
          preferredFoot: Foot.values[i % Foot.values.length],
          isVerified: i % 5 == 0,
          createdByUserId: createdBy,
          paceAcceleration: rating(10, i),
          topSpeed: rating(12, i),
          stamina: rating(14, i),
          strength: rating(16, i),
          agility: rating(18, i),
          balance: rating(20, i),
          jump: rating(22, i),
          passingShort: rating(24, i),
          passingLong: rating(26, i),
          progressivePass: rating(28, i),
          firstTouch: rating(30, i),
          ballControl: rating(32, i),
          dribbling: rating(34, i),
          crossing: rating(36, i),
          finishing: rating(38, i),
          shotPower: rating(40, i),
          heading: rating(42, i),
          tackling: rating(44, i),
          interception: rating(46, i),
          positioning: rating(48, i),
          aerialDuels: rating(50, i),
          groundDuels: rating(52, i),
          weakFootQuality: rating(54, i),
          buildUp: rating(56, i),
          pressResistance: rating(58, i),
          decisionMaking: rating(60, i),
          scanning: rating(62, i),
          offBallMovement: rating(64, i),
          defensiveLine: rating(66, i),
          pressing: rating(68, i),
          recoveryRuns: rating(70, i),
          composure: rating(72, i),
          aggression: rating(74, i),
          leadership: rating(76, i),
          teamwork: rating(78, i),
          resilience: rating(80, i),
          coachability: rating(82, i),
          professionalism: rating(84, i),
          gameIQ: rating(86, i),
          riskTaking: rating(88, i),
          discipline: rating(90, i),
          styleTags: const ['Versátil', 'Rápido', 'Tático'],
          roles: const ['Titular em observação'],
          strengths: const ['Intensidade', 'Passe'],
          weaknesses: const ['Regularidade'],
          bestSystems: const ['4-3-3', '4-2-3-1'],
          bestBlock: TacticalBlock.values[i % TacticalBlock.values.length],
          description:
              'Perfil gerado para ampliar a base de talentos da plataforma.',
          estimatedValueMin: 300000 + (i * 50000),
          estimatedValueMax: 700000 + (i * 60000),
          salaryMin: 20000 + (i * 500),
          salaryMax: 40000 + (i * 800),
          potential: Potential.values[i % Potential.values.length],
          transferRisk: TransferRisk.values[i % TransferRisk.values.length],
          isReadyToLevelUp: i % 4 == 0,
          injuryHistory: const [],
          injuryRisk: InjuryRisk.values[i % InjuryRisk.values.length],
          photoUrl:
              'https://via.placeholder.com/200/1E40AF/FFFFFF?text=Player+$i',
          highlightVideos: [
            'video_${i}_1',
            'video_${i}_2',
          ],
          createdAt: DateTime.now().subtract(Duration(days: i * 2)),
          updatedAt: DateTime.now(),
          followers: 200 + i * 12,
          savedByUsers: const [],
        ),
      );
    }

    return [...basePlayers, ...extraPlayers];
  }

  static List<Post> generateMockPosts() {
    final basePosts = [
      Post(
        id: 'post_1',
        authorId: 'user_1',
        linkedPlayerId: 'player_1',
        mediaType: 'video',
        mediaUrl:
            'https://via.placeholder.com/300x500/FF6B6B/FFFFFF?text=Marcus+Silva',
        caption: 'Que finalização do Marcus! Impecável na área. 🔥⚽',
        tags: ['finalizacao', 'flamengo', 'gol'],
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        likes: 2341,
        comments: 156,
        reposts: 89,
        likedByUsers: [],
        savedByUsers: [],
        repostedByUsers: [],
      ),
      Post(
        id: 'post_2',
        authorId: 'user_2',
        linkedPlayerId: 'player_2',
        mediaType: 'photo',
        mediaUrl:
            'https://via.placeholder.com/300x500/4ECDC4/FFFFFF?text=Pedro+Rocha',
        caption:
            'Defesa aérea impressionante do Rock. Liderança em todos os duelos.',
        tags: ['defesa', 'zagueiro', 'benfica'],
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        likes: 1876,
        comments: 124,
        reposts: 67,
        likedByUsers: [],
        savedByUsers: [],
        repostedByUsers: [],
      ),
      Post(
        id: 'post_3',
        authorId: 'user_3',
        linkedPlayerId: 'player_3',
        mediaType: 'video',
        mediaUrl:
            'https://via.placeholder.com/300x500/95E1D3/FFFFFF?text=Joao+Costa',
        caption:
            'Passes progressivos impecáveis. A visão de jogo do João é rara nessa idade.',
        tags: ['meia', 'passes', 'vasco'],
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        likes: 3456,
        comments: 201,
        reposts: 145,
        likedByUsers: [],
        savedByUsers: [],
        repostedByUsers: [],
      ),
      Post(
        id: 'post_4',
        authorId: 'user_4',
        linkedPlayerId: 'player_4',
        mediaType: 'video',
        mediaUrl:
            'https://via.placeholder.com/300x500/F38181/FFFFFF?text=Felipe+Santos',
        caption:
            '⚡ Velocidade ABSURDA! Felipe pulveriza a defesa em 3 segundos.',
        tags: ['ponta', 'velocidade', 'dribble'],
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        likes: 5621,
        comments: 324,
        reposts: 212,
        likedByUsers: [],
        savedByUsers: [],
        repostedByUsers: [],
      ),
      Post(
        id: 'post_5',
        authorId: 'user_5',
        linkedPlayerId: 'player_5',
        mediaType: 'photo',
        mediaUrl:
            'https://via.placeholder.com/300x500/AA96DA/FFFFFF?text=Rafael+Borges',
        caption:
            'Distribuição limpa e segurança sob pressão. Rafael segue sendo confiável.',
        tags: ['goleiro', 'palmeiras', 'defesa'],
        createdAt: DateTime.now().subtract(const Duration(hours: 15)),
        likes: 1243,
        comments: 87,
        reposts: 34,
        likedByUsers: [],
        savedByUsers: [],
        repostedByUsers: [],
      ),
    ];

    final extraPosts = <Post>[];
    for (int i = basePosts.length + 1; i <= 120; i++) {
      final playerId = 'player_${((i - 1) % 60) + 1}';
      final authorId = 'user_${((i - 1) % 30) + 1}';
      final mediaType = i % 2 == 0 ? 'photo' : 'video';
      extraPosts.add(
        Post(
          id: 'post_$i',
          authorId: authorId,
          linkedPlayerId: playerId,
          mediaType: mediaType,
          mediaUrl:
              'https://via.placeholder.com/300x500/0F172A/FFFFFF?text=Post+$i',
          caption: 'Destaque do jogador $playerId em ação. ⚽',
          tags: ['destaque', 'scout', 'futly'],
          createdAt: DateTime.now().subtract(Duration(hours: i * 2)),
          likes: 50 + (i * 7),
          comments: 5 + (i % 20),
          reposts: 2 + (i % 10),
          likedByUsers: const [],
          savedByUsers: const [],
          repostedByUsers: const [],
        ),
      );
    }

    return [...basePosts, ...extraPosts];
  }

  static List<User> generateMockUsers() {
    final baseUsers = [
      User(
        id: 'user_1',
        name: 'Futly Scout',
        email: 'scout@futly.com',
        bio: 'Profissional de identificação de talentos',
        avatarUrl: 'https://via.placeholder.com/100/1E40AF/FFFFFF?text=FS',
        isVerified: true,
        createdAt: DateTime(2020, 1, 15),
        postsCount: 342,
        playersCreatedCount: 87,
        savesCount: 156,
        followers: ['user_2', 'user_3', 'user_4'],
        following: ['user_5', 'user_6'],
      ),
      User(
        id: 'user_2',
        name: 'João Analyst',
        email: 'joao@futly.com',
        bio: 'Analista de performance',
        avatarUrl: 'https://via.placeholder.com/100/059669/FFFFFF?text=JA',
        isVerified: true,
        createdAt: DateTime(2021, 3, 22),
        postsCount: 256,
        playersCreatedCount: 64,
        savesCount: 98,
        followers: ['user_1', 'user_3'],
        following: ['user_1', 'user_4'],
      ),
      User(
        id: 'user_3',
        name: 'Maria Scout',
        email: 'maria@futly.com',
        bio: 'Observadora de talentos emergentes',
        avatarUrl: 'https://via.placeholder.com/100/DC2626/FFFFFF?text=MS',
        isVerified: false,
        createdAt: DateTime(2022, 6, 10),
        postsCount: 128,
        playersCreatedCount: 32,
        savesCount: 45,
        followers: ['user_1'],
        following: ['user_1', 'user_2'],
      ),
      User(
        id: 'user_4',
        name: 'Carlos Mendes',
        email: 'carlos@futly.com',
        bio: 'Agente de jogadores',
        avatarUrl: 'https://via.placeholder.com/100/EA580C/FFFFFF?text=CM',
        isVerified: true,
        createdAt: DateTime(2021, 9, 5),
        postsCount: 89,
        playersCreatedCount: 45,
        savesCount: 67,
        followers: [],
        following: ['user_1', 'user_2'],
      ),
      User(
        id: 'user_5',
        name: 'Pedro Técnico',
        email: 'pedro@futly.com',
        bio: 'Técnico e observador de talentos',
        avatarUrl: 'https://via.placeholder.com/100/16A34A/FFFFFF?text=PT',
        isVerified: false,
        createdAt: DateTime(2022, 11, 20),
        postsCount: 76,
        playersCreatedCount: 19,
        savesCount: 32,
        followers: [],
        following: [],
      ),
    ];

    final extraUsers = <User>[];
    for (int i = baseUsers.length + 1; i <= 30; i++) {
      extraUsers.add(
        User(
          id: 'user_$i',
          name: 'Usuário $i',
          email: 'user$i@futly.com',
          bio: 'Observador e fã de futebol #$i',
          avatarUrl: 'https://via.placeholder.com/100/1E40AF/FFFFFF?text=U$i',
          isVerified: i % 4 == 0,
          createdAt: DateTime(2021, (i % 12) + 1, (i % 28) + 1),
          postsCount: 10 + i * 2,
          playersCreatedCount: 2 + (i % 6),
          savesCount: 5 + (i % 10),
          followers: const [],
          following: const [],
        ),
      );
    }

    return [...baseUsers, ...extraUsers];
  }

  static List<Comment> generateMockComments() {
    final baseComments = [
      Comment(
        id: 'comment_1',
        postId: 'post_1',
        authorId: 'user_2',
        text: 'Que precisão! Este jogador tem tudo para ser fera.',
        createdAt: DateTime.now().subtract(const Duration(hours: 1)),
        likes: 234,
        likedByUsers: [],
      ),
      Comment(
        id: 'comment_2',
        postId: 'post_1',
        authorId: 'user_3',
        text: 'Excelente movimentação de área. Já está no meu watchlist!',
        createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
        likes: 178,
        likedByUsers: [],
      ),
    ];

    final extraComments = <Comment>[];
    for (int i = baseComments.length + 1; i <= 200; i++) {
      final postId = 'post_${((i - 1) % 120) + 1}';
      final authorId = 'user_${((i - 1) % 30) + 1}';
      extraComments.add(
        Comment(
          id: 'comment_$i',
          postId: postId,
          authorId: authorId,
          text: 'Comentário $i sobre o post $postId.',
          createdAt: DateTime.now().subtract(Duration(minutes: i * 3)),
          likes: i % 20,
          likedByUsers: const [],
        ),
      );
    }

    return [...baseComments, ...extraComments];
  }
}
